version: '3.8'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_DB: homework-todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
